// Íconos que se guardan por nombre en la base de datos (cuentas, categorías, metas), de Lucide
// (lucide.dev, licencia ISC). Sin logos de marcas ni de bancos.
// Los nombres no se pueden cambiar ni quitar: los datos ya guardados y las copias de seguridad
// los usan. Sí se pueden agregar nuevos y cambiar el dibujo de uno existente.
import {
  Activity,
  AirVent,
  Anchor,
  Archive,
  Apple,
  Award,
  BadgeDollarSign,
  BadgePercent,
  Baby,
  Bandage,
  Banknote,
  Bath,
  Bed,
  Beef,
  Beer,
  Bell,
  Bike,
  Bird,
  Bone,
  Book,
  BookOpen,
  Brain,
  Briefcase,
  BriefcaseMedical,
  Building,
  Building2,
  BusFront,
  CakeSlice,
  Calculator,
  Calendar,
  CalendarClock,
  Camera,
  Candy,
  Car,
  CarTaxiFront,
  Caravan,
  Carrot,
  Cat,
  ChartColumn,
  ChartLine,
  ChartPie,
  ChefHat,
  Church,
  CircleDollarSign,
  Clapperboard,
  Clock,
  Cloud,
  Coffee,
  Coins,
  Compass,
  Cookie,
  CookingPot,
  CreditCard,
  Croissant,
  Crown,
  CupSoda,
  Dices,
  Dog,
  Drama,
  Drill,
  Droplet,
  Drumstick,
  Dumbbell,
  Egg,
  Euro,
  Factory,
  Fan,
  FileText,
  Fish,
  Flag,
  Flame,
  Flower2,
  Folder,
  Fuel,
  Gamepad2,
  Gem,
  Gift,
  Glasses,
  Globe,
  GraduationCap,
  Guitar,
  Hamburger,
  Hammer,
  HandCoins,
  HandHeart,
  Handshake,
  Headphones,
  Heart,
  HeartPulse,
  Hospital,
  Hotel,
  House,
  IceCreamCone,
  Key,
  Lamp,
  Landmark,
  Laptop,
  LayoutGrid,
  Leaf,
  Library,
  Lightbulb,
  Lock,
  Luggage,
  Mail,
  Map,
  MapPin,
  Martini,
  Medal,
  Milk,
  Monitor,
  Motorbike,
  Mountain,
  Music,
  Newspaper,
  NotebookPen,
  Package,
  PaintRoller,
  Palette,
  PartyPopper,
  PawPrint,
  Phone,
  PiggyBank,
  Pill,
  Pizza,
  Plane,
  Plug,
  Printer,
  Puzzle,
  Rabbit,
  Receipt,
  ReceiptText,
  Recycle,
  Refrigerator,
  Rocket,
  Route,
  Sailboat,
  Salad,
  Sandwich,
  Scale,
  School,
  Scissors,
  Shield,
  ShieldCheck,
  Ship,
  Shirt,
  ShoppingBag,
  ShoppingBasket,
  ShoppingCart,
  ShowerHead,
  Smartphone,
  Smile,
  Sofa,
  Soup,
  Sparkles,
  SprayCan,
  Sprout,
  SquareParking,
  Star,
  Stethoscope,
  Store,
  Sun,
  Syringe,
  Tag,
  Target,
  Tent,
  Thermometer,
  Ticket,
  TicketsPlane,
  ToyBrick,
  TrainFront,
  TreePalm,
  TreePine,
  TrendingUp,
  Trophy,
  Truck,
  Tv,
  UserRound,
  Users,
  Utensils,
  Vault,
  Volleyball,
  Wallet,
  WalletCards,
  Warehouse,
  Watch,
  WashingMachine,
  Wifi,
  Wine,
  Wrench,
  Zap,
} from 'lucide-react';

// [nombre guardado, ícono, etiqueta para lectores de pantalla]. En el panel "Elegir ícono"
// se muestran en estos grupos y en este orden.
export const GRUPOS_ICONOS = [
  {
    titulo: 'Dinero y cuentas',
    iconos: [
      ['banco', Landmark, 'Banco'],
      ['billetera', Wallet, 'Billetera'],
      ['billetera-tarjetas', WalletCards, 'Billetera con tarjetas'],
      ['tarjeta', CreditCard, 'Tarjeta'],
      ['efectivo', Banknote, 'Billete'],
      ['monedas', Coins, 'Monedas'],
      ['moneda', CircleDollarSign, 'Moneda'],
      ['signo-pesos', BadgeDollarSign, 'Signo de pesos'],
      ['euro', Euro, 'Euro'],
      ['alcancia', PiggyBank, 'Alcancía'],
      ['caja-fuerte', Vault, 'Caja fuerte'],
      ['mano-monedas', HandCoins, 'Mano con monedas'],
      ['tendencia', TrendingUp, 'Tendencia'],
      ['grafico-linea', ChartLine, 'Gráfico de línea'],
      ['grafico-barras', ChartColumn, 'Gráfico de barras'],
      ['pastel', ChartPie, 'Gráfico circular'],
      ['porcentaje', BadgePercent, 'Porcentaje'],
      ['recibo', Receipt, 'Recibo'],
      ['factura', ReceiptText, 'Factura'],
      ['calculadora', Calculator, 'Calculadora'],
      ['balanza', Scale, 'Balanza'],
      ['diamante', Gem, 'Diamante'],
    ],
  },
  {
    titulo: 'Comida y bebida',
    iconos: [
      ['carrito', ShoppingCart, 'Mercado'],
      ['canasta', ShoppingBasket, 'Canasta'],
      ['cubiertos', Utensils, 'Restaurante'],
      ['cocina', ChefHat, 'Cocina'],
      ['olla', CookingPot, 'Olla'],
      ['cafe', Coffee, 'Café'],
      ['pizza', Pizza, 'Pizza'],
      ['hamburguesa', Hamburger, 'Hamburguesa'],
      ['sandwich', Sandwich, 'Sándwich'],
      ['sopa', Soup, 'Sopa'],
      ['carne', Beef, 'Carne'],
      ['pollo', Drumstick, 'Pollo'],
      ['pescado', Fish, 'Pescado'],
      ['huevos', Egg, 'Huevos'],
      ['ensalada', Salad, 'Ensalada'],
      ['fruta', Apple, 'Fruta'],
      ['verdura', Carrot, 'Verdura'],
      ['panaderia', Croissant, 'Panadería'],
      ['torta', CakeSlice, 'Torta'],
      ['helado', IceCreamCone, 'Helado'],
      ['galletas', Cookie, 'Galletas'],
      ['dulces', Candy, 'Dulces'],
      ['leche', Milk, 'Leche'],
      ['gaseosa', CupSoda, 'Gaseosa'],
      ['cerveza', Beer, 'Cerveza'],
      ['vino', Wine, 'Vino'],
      ['coctel', Martini, 'Coctel'],
    ],
  },
  {
    titulo: 'Compras',
    iconos: [
      ['bolsa', ShoppingBag, 'Bolsa'],
      ['tienda', Store, 'Tienda'],
      ['ropa', Shirt, 'Ropa'],
      ['etiqueta', Tag, 'Etiqueta'],
      ['regalo', Gift, 'Regalo'],
      ['paquete', Package, 'Paquete'],
      ['reloj-pulsera', Watch, 'Reloj de pulsera'],
      ['gafas', Glasses, 'Gafas'],
      ['celular', Smartphone, 'Celular'],
      ['portatil', Laptop, 'Portátil'],
      ['computador', Monitor, 'Computador'],
      ['audifonos', Headphones, 'Audífonos'],
      ['camara', Camera, 'Cámara'],
      ['televisor', Tv, 'Televisor'],
    ],
  },
  {
    titulo: 'Transporte',
    iconos: [
      ['gasolina', Fuel, 'Gasolina'],
      ['carro', Car, 'Carro'],
      ['taxi', CarTaxiFront, 'Taxi'],
      ['bus', BusFront, 'Bus'],
      ['moto', Motorbike, 'Moto'],
      ['bicicleta', Bike, 'Bicicleta'],
      ['tren', TrainFront, 'Tren'],
      ['avion', Plane, 'Avión'],
      ['barco', Ship, 'Barco'],
      ['parqueadero', SquareParking, 'Parqueadero'],
      ['ruta', Route, 'Ruta'],
      ['ubicacion', MapPin, 'Ubicación'],
      ['camion', Truck, 'Camión'],
      ['taller', Wrench, 'Taller'],
    ],
  },
  {
    titulo: 'Hogar',
    iconos: [
      ['casa', House, 'Casa'],
      ['edificio', Building, 'Edificio'],
      ['llave', Key, 'Llave'],
      ['sofa', Sofa, 'Sofá'],
      ['cama', Bed, 'Cama'],
      ['lampara', Lamp, 'Lámpara'],
      ['lavadora', WashingMachine, 'Lavadora'],
      ['nevera', Refrigerator, 'Nevera'],
      ['martillo', Hammer, 'Martillo'],
      ['taladro', Drill, 'Taladro'],
      ['pintura', PaintRoller, 'Pintura'],
      ['limpieza', SprayCan, 'Limpieza'],
      ['ducha', ShowerHead, 'Ducha'],
      ['bano', Bath, 'Baño'],
      ['planta', Sprout, 'Planta'],
      ['flor', Flower2, 'Flor'],
    ],
  },
  {
    titulo: 'Servicios',
    iconos: [
      ['rayo', Zap, 'Energía'],
      ['bombillo', Lightbulb, 'Bombillo'],
      ['agua', Droplet, 'Agua'],
      ['gas', Flame, 'Gas'],
      ['internet', Wifi, 'Internet'],
      ['telefono', Phone, 'Teléfono'],
      ['enchufe', Plug, 'Enchufe'],
      ['ventilador', Fan, 'Ventilador'],
      ['aire', AirVent, 'Aire acondicionado'],
      ['correo', Mail, 'Correo'],
      ['nube', Cloud, 'Nube'],
      ['pago-periodico', CalendarClock, 'Pago periódico'],
      ['documento', FileText, 'Documento'],
      ['candado', Lock, 'Candado'],
    ],
  },
  {
    titulo: 'Salud y cuidado',
    iconos: [
      ['corazon', Heart, 'Corazón'],
      ['salud', HeartPulse, 'Salud'],
      ['medicamentos', Pill, 'Medicamentos'],
      ['medico', Stethoscope, 'Médico'],
      ['hospital', Hospital, 'Hospital'],
      ['botiquin', BriefcaseMedical, 'Botiquín'],
      ['vacuna', Syringe, 'Vacuna'],
      ['curita', Bandage, 'Curita'],
      ['termometro', Thermometer, 'Termómetro'],
      ['gimnasio', Dumbbell, 'Gimnasio'],
      ['actividad', Activity, 'Actividad'],
      ['peluqueria', Scissors, 'Peluquería'],
      ['belleza', Sparkles, 'Belleza'],
      ['bienestar', Smile, 'Bienestar'],
      ['mente', Brain, 'Mente'],
    ],
  },
  {
    titulo: 'Ocio',
    iconos: [
      ['estrella', Star, 'Estrella'],
      ['cine', Clapperboard, 'Cine'],
      ['boleta', Ticket, 'Boleta'],
      ['musica', Music, 'Música'],
      ['guitarra', Guitar, 'Guitarra'],
      ['teatro', Drama, 'Teatro'],
      ['fiesta', PartyPopper, 'Fiesta'],
      ['videojuegos', Gamepad2, 'Videojuegos'],
      ['juegos', Dices, 'Juegos de mesa'],
      ['rompecabezas', Puzzle, 'Rompecabezas'],
      ['deporte', Volleyball, 'Deporte'],
      ['trofeo', Trophy, 'Trofeo'],
      ['arte', Palette, 'Arte'],
      ['libro', Book, 'Libro'],
      ['prensa', Newspaper, 'Prensa'],
    ],
  },
  {
    titulo: 'Viajes',
    iconos: [
      ['maleta', Luggage, 'Maleta'],
      ['hotel', Hotel, 'Hotel'],
      ['tiquete-avion', TicketsPlane, 'Tiquete de avión'],
      ['mapa', Map, 'Mapa'],
      ['brujula', Compass, 'Brújula'],
      ['mundo', Globe, 'Mundo'],
      ['playa', TreePalm, 'Playa'],
      ['montana', Mountain, 'Montaña'],
      ['camping', Tent, 'Camping'],
      ['casa-rodante', Caravan, 'Casa rodante'],
      ['velero', Sailboat, 'Velero'],
      ['ancla', Anchor, 'Ancla'],
      ['sol', Sun, 'Sol'],
    ],
  },
  {
    titulo: 'Estudio y trabajo',
    iconos: [
      ['graduacion', GraduationCap, 'Graduación'],
      ['estudio', BookOpen, 'Estudio'],
      ['colegio', School, 'Colegio'],
      ['biblioteca', Library, 'Biblioteca'],
      ['cuaderno', NotebookPen, 'Cuaderno'],
      ['maletin', Briefcase, 'Maletín'],
      ['negocio', Handshake, 'Negocio'],
      ['oficina', Building2, 'Oficina'],
      ['impresora', Printer, 'Impresora'],
      ['fabrica', Factory, 'Fábrica'],
      ['bodega', Warehouse, 'Bodega'],
      ['emprendimiento', Rocket, 'Emprendimiento'],
      ['premio', Award, 'Premio'],
      ['medalla', Medal, 'Medalla'],
    ],
  },
  {
    titulo: 'Familia y mascotas',
    iconos: [
      ['familia', Users, 'Familia'],
      ['persona', UserRound, 'Persona'],
      ['bebe', Baby, 'Bebé'],
      ['juguete', ToyBrick, 'Juguete'],
      ['donacion', HandHeart, 'Donación'],
      ['iglesia', Church, 'Iglesia'],
      ['mascota', PawPrint, 'Mascota'],
      ['perro', Dog, 'Perro'],
      ['gato', Cat, 'Gato'],
      ['ave', Bird, 'Ave'],
      ['conejo', Rabbit, 'Conejo'],
      ['hueso', Bone, 'Hueso'],
    ],
  },
  {
    titulo: 'Otros',
    iconos: [
      ['cuadricula', LayoutGrid, 'Cuadrícula'],
      ['escudo', Shield, 'Escudo'],
      ['seguro', ShieldCheck, 'Seguro'],
      ['diana', Target, 'Meta'],
      ['corona', Crown, 'Corona'],
      ['campana', Bell, 'Campana'],
      ['calendario', Calendar, 'Calendario'],
      ['reloj', Clock, 'Reloj'],
      ['hoja', Leaf, 'Hoja'],
      ['arbol', TreePine, 'Árbol'],
      ['reciclaje', Recycle, 'Reciclaje'],
      ['carpeta', Folder, 'Carpeta'],
      ['archivo', Archive, 'Archivo'],
      ['bandera', Flag, 'Bandera'],
    ],
  },
];

const TODOS = GRUPOS_ICONOS.flatMap((grupo) => grupo.iconos);

export const ICONOS = Object.fromEntries(TODOS.map(([nombre, Icono]) => [nombre, Icono]));

// Para lectores de pantalla.
export const ETIQUETAS_ICONO = Object.fromEntries(TODOS.map(([nombre, , etiqueta]) => [nombre, etiqueta]));

// Los que se ven de entrada en los formularios (el resto, en "Más íconos").
export const ICONOS_CUENTA = ['banco', 'billetera', 'tarjeta', 'efectivo', 'alcancia', 'monedas', 'tendencia'];
export const ICONOS_TARJETA = ['tarjeta', 'bolsa', 'carrito', 'regalo', 'estrella', 'avion', 'maleta'];
export const ICONOS_META = ['portatil', 'escudo', 'tiquete-avion', 'casa', 'regalo', 'estrella', 'alcancia'];

export const ICONOS_CATEGORIA = [
  'carrito',
  'cubiertos',
  'gasolina',
  'bus',
  'casa',
  'rayo',
  'corazon',
  'libro',
  'estrella',
  'ropa',
  'regalo',
  'maletin',
  'portatil',
  'tendencia',
  'cuadricula',
];

// Un nombre desconocido (de una versión futura, por ejemplo) se ve como la cuadrícula.
export function IconoPorNombre({ nombre, tamano = 22, grosor = 2 }) {
  const Icono = ICONOS[nombre] ?? ICONOS.cuadricula;
  return <Icono size={tamano} strokeWidth={grosor} aria-hidden="true" focusable="false" />;
}
